### ISSUE TITLE
Boot Freeze on old RPi 

### ISSUE THREAD

**Issue by maurorappa** [guysoft/RealtimePi#13] opened 2018-11-19 21:16 UTC
I have a 2011 RPi (Hardware	: BCM2835 Revision	: 000f) which freezes during boo after few blinks.
It's no overclocked and work absolutely fine with a Debian on it.
See picture.
![img_2869](https://user-images.githubusercontent.com/4287381/48735475-5ac93d00-ec40-11e8-91e2-d004e59e0482.JPG)
is it simply too old?

Cheers

**Comment by guysoft** [comment] 2018-11-20 10:02
What version of RealtimePi are you using?
It should work, since both ARMv6 and ARMv7 kernels are available. At least according to the Rpi documentation.
Does it run normal raspbian lite?

**Comment by guysoft** [comment] 2018-11-26 14:33
Closing if no reply

**Comment by guysoft** [comment] 2018-12-16 00:10
There might be an issue with the armv6 kernel, can you post what you see on screen? Prephebly for the 0.4 nightly.

**Comment by oxbown** [comment] 2019-07-02 18:47
Same issue with a raspberry pi 2 v1.2.
Freezes during boo after few blinks, no code on screen only the pi logo on the corner...

**Comment by oxbown** [comment] 2019-07-02 19:07
Tested all the versions:
V0.1 and V0.2 works!
V0.3 and current version of the V0.4 don't work!

My Raspberry Pi 2 is a ARMv6 BCM2835 (2014 model)

**Comment by guysoft** [comment] 2019-07-03 11:19
@oxbown Thanks for reporting. How far did the boot fail on 0.4? Did you try the release candidate or the nightly?

**Comment by oxbown** [comment] 2019-07-03 14:39
> @oxbown Thanks for reporting. How far did the boot fail on 0.4? Did you try the release candidate or the nightly?

I used this version:
http://unofficialpi.org/Distros/RealtimePi/nightly/2019-05-14_2019-04-08-realtimepi-stretch-lite-0.4.0.zip

Its freezes like v0.3 , 3 yellow blinks and in the screen only the raspberry logo.

**Comment by guysoft** [comment] 2019-07-04 13:59
Ok, you can try if you like the last nightly:
http://unofficialpi.org/Distros/RealtimePi/nightly/2019-06-29_2019-06-20-realtimepi-buster-lite-0.4.0.zip

But I am really just betting here, I have no way of debugging what is going wrong. You can try posting your results for the nightly I just posted here, because this issue has kernel developers who might help you debug what is going wrong: https://github.com/raspberrypi/linux/issues/2943

**Comment by oxbown** [comment] 2019-07-10 06:50
> Ok, you can try if you like the last nightly:
> http://unofficialpi.org/Distros/RealtimePi/nightly/2019-06-29_2019-06-20-realtimepi-buster-lite-0.4.0.zip
> 
> But I am really just betting here, I have no way of debugging what is going wrong. You can try posting your results for the nightly I just posted here, because this issue has kernel developers who might help you debug what is going wrong: [raspberrypi/linux#2943](https://github.com/raspberrypi/linux/issues/2943)
> 
> Also, you might be able to get more debug output if you use `console=serial0,115200 kgdboc=ttyS0,115200` , it should give you more info, see what how it changes the output in my post in the issue above in this comment.

Hello!
It seems to work! The raspberry boots... but ethernet and USB doesn't work.
This weekend i´ll try to do more test.

**Comment by guysoft** [comment] 2019-07-10 09:47
Ok, the usb and ethernet nto working is a known issue.
You can try setting in ``/boot/cmdline.txt`` ``dwc_otg.lpm_enable=1`` to ``dwc_otg.lpm_enable=0``.
If it boots you should have USB.

**Comment by oxbown** [comment] 2019-07-10 18:44
Well well well... I found something interesting.
If I change the value of dwc_otg.lpm_enable to 0 the Realtimepi 0.4 not boots, it freezes like 0,3 version.
I flashed back the version 0.3 on the SD card and them I changed the dwc_otg.lpm_enable to 1....and.....boom version 0.3 is running on my raspberry B v2... but without usb and ethernet.
I think that the problem is with this parameter.

**Comment by guysoft** [comment] 2019-07-10 22:21
It means that the ``usb-dwc_otg-fix`` patch is not working for the old Pi kernel on 0.3.

That setup came from this commit: https://github.com/raspberrypi/linux/issues/2943#issuecomment-506483290

Will report back there

**Comment by nsf747** [comment] 2019-08-24 07:21
> Well well well... I found something interesting.
> If I change the value of dwc_otg.lpm_enable to 0 the Realtimepi 0.4 not boots, it freezes like 0,3 version.
> I flashed back the version 0.3 on the SD card and them I changed the dwc_otg.lpm_enable to 1....and.....boom version 0.3 is running on my raspberry B v2... but without usb and ethernet.
> I think that the problem is with this parameter.

Hey, I'm facing the same issue on my RPi 2B. Im running the latest OS image 2019-08-07_2019-07-10-realtimepi-buster-lite-0.4.0. 
When I change value of `dwc_otg.lpm_enable` to 0 it freezes at this line

`[    5.657047] systemd[1]: Listening on fsck to fsckd communication Socket.`

When I change value of `dwc_otg.lpm_enable` to 1 it boots but without USB and ethernet.

**Comment by nsf747** [comment] 2019-08-24 07:55
> Well well well... I found something interesting.
> If I change the value of dwc_otg.lpm_enable to 0 the Realtimepi 0.4 not boots, it freezes like 0,3 version.
> I flashed back the version 0.3 on the SD card and them I changed the dwc_otg.lpm_enable to 1....and.....boom version 0.3 is running on my raspberry B v2... but without usb and ethernet.
> I think that the problem is with this parameter.

Hey, I'm facing a similar issue with my RPi2B. I'm running 2019-08-07_2019-07-10-realtimepi-buster-lite-0.4.0. 

When the value of `dwc_otg.lpm_enable` to 1 it boots but with USB and ethernet disabled. 

When I set the value of `dwc_otg.lpm_enable` to 0 it hangs with the ethernet cable attached. But if I remove the ethernet cable it boots up and runs fine. And if I connect the cable again after booting up it runs for a few seconds and then hangs.

**Comment by guysoft** [comment] 2019-08-25 07:54
@nsf747 Try the latest nightly and report. If you get agait then it means ``usb-dwc_otg-fix`` might need an update. Reporting would help @TiejunChina know there is an issue that needs to be fixed.

**Comment by guysoft** [comment] 2019-12-17 15:03
Closing due to no reply

**Closed by guysoft** 2019-12-17 15:03 UTC
